config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :news
  resources :authors
  resources :news_categories

  # API ENDPOINTS
  get '/api/news' => 'api_news#get_news'
  get '/api/news/:id' => 'api_news#get_single_news'
  get '/api/author' => 'api_news#get_authors'
  get '/api/news-by-author/:id' => 'api_news#get_news_by_author_id'
  get '/api/author/:id' => 'api_news#get_author'
  get '/api/news-category' => 'api_news#get_news_category'
  get '/api/search' => 'api_news#get_search'

  get '/', to: redirect('/news')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/news.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: news
#
#  id                 :bigint           not null, primary key
#  title              :string
#  headline           :string
#  image              :string
#  date               :date
#  description        :text
#  authors_id         :bigint
#  news_categories_id :bigint
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#

class News < ApplicationRecord
  # has_many :author
  # has_many :news_category
  belongs_to :author, class_name: 'Author', optional: true
  belongs_to :news_category, class_name: 'NewsCategory', optional: true
end

app/controllers/news_controller.rb
# frozen_string_literal: true

class NewsController < ApplicationController
  before_action :set_news, only: %i[show edit update destroy]

  # GET /news
  # GET /news.json
  def index
    @news = News.all
  end

  # GET /news/1
  # GET /news/1.json
  def show; end

  # GET /news/new
  def new
    @news = News.new
  end

  # GET /news/1/edit
  def edit; end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(news_params)

    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: 'News was successfully created.' }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to @news, notice: 'News was successfully updated.' }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news.destroy
    respond_to do |format|
      format.html { redirect_to news_index_url, notice: 'News was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_news
    @news = News.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def news_params
    params.require(:news).permit(:title, :headline, :image, :date, :description, :authors_id, :news_categories_id)
  end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/_form.html.erb
<%= form_with(model: news, local: true) do |form| %>
  <% if news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(news.errors.count, "error") %> prohibited this news from being saved:</h2>
      <ul>
        <% news.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="field">
    <%= form.label :headline %>
    <%= form.text_field :headline %>
  </div>
  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image %>
    <% if news.image.present? %>
      <br>
      <br>
      <%= image_tag news.image, width: 300 %>
      <br>
      <br>
    <% end %>
  </div>
  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>
  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>
  <div class="field">
    <%= form.label :authors_id %>
    <%= form.select :authors_id, Author.pluck(:name, :id), :include_blank => true %>
  </div>
  <div class="field">
    <%= form.label :news_categories_id %>
    <%= form.select :news_categories_id, NewsCategory.pluck(:name, :id), :include_blank => true %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/news/edit.html.erb
<h1>Editing News</h1>

<%= render 'form', news: @news %>

<%= link_to 'Show', @news %> |
<%= link_to 'Back', news_index_path %>

app/views/news/index.html.erb
<p id="notice"><%= notice %></p>
<h1>News</h1>
<%= link_to '+ New', new_news_path, class: "controls-link block" %>
<br>
<br>
<br>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Headline</th>
      <th>Image</th>
      <th>Date</th>
      <th>Description</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @news.each do |news| %>
      <tr>
        <td><%= news.title %></td>
        <td><%= "#{news.headline.first(80)} (...)" %></td>
        <td><%= news.image %></td>
        <td><%= news.date %></td>
        <td><%= "#{news.description.first(100)} (...)" %></td>
        <td><%= link_to 'Show', news %></td>
        <td><%= link_to 'Edit', edit_news_path(news) %></td>
        <td><%= link_to 'Destroy', news, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/news/new.html.erb
<h1>New News</h1>

<%= render 'form', news: @news %>

<%= link_to 'Back', news_index_path %>

app/views/news/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Title:</strong>
  <%= @news.title %>
</p>
<p>
  <strong>Headline:</strong>
  <%= @news.headline %>
</p>
<% if @news.image.present? %>
  <p>
    <strong>Image:</strong>
    <%= image_tag @news.image, width: 300 %>
  </p>
<% end %>
<p>
  <strong>Date:</strong>
  <%= @news.date %>
</p>
<p>
  <strong>Description:</strong>
  <%= @news.description %>
</p>
<p>
  <strong>Authors:</strong>
  <%= Author.find(@news.authors_id).name %>
</p>
<p>
  <strong>News categories:</strong>
  <%= NewsCategory.find(@news.news_categories_id).name %>
</p>
<%= link_to 'Edit', edit_news_path(@news) %> |
<%= link_to 'Back', news_index_path %>