config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :news
  resources :authors
  resources :news_categories

  # API ENDPOINTS
  get '/api/news' => 'api_news#get_news'
  get '/api/news/:id' => 'api_news#get_single_news'
  get '/api/author' => 'api_news#get_authors'
  get '/api/news-by-author/:id' => 'api_news#get_news_by_author_id'
  get '/api/author/:id' => 'api_news#get_author'
  get '/api/news-category' => 'api_news#get_news_category'
  get '/api/search' => 'api_news#get_search'

  get '/', to: redirect('/news')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/news_category.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: news_categories
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class NewsCategory < ApplicationRecord
end

app/controllers/news_categories_controller.rb
class NewsCategoriesController < ApplicationController
  before_action :set_news_category, only: [:show, :edit, :update, :destroy]

  # GET /news_categories
  # GET /news_categories.json
  def index
    @news_categories = NewsCategory.all
  end

  # GET /news_categories/1
  # GET /news_categories/1.json
  def show
  end

  # GET /news_categories/new
  def new
    @news_category = NewsCategory.new
  end

  # GET /news_categories/1/edit
  def edit
  end

  # POST /news_categories
  # POST /news_categories.json
  def create
    @news_category = NewsCategory.new(news_category_params)

    respond_to do |format|
      if @news_category.save
        format.html { redirect_to @news_category, notice: 'News category was successfully created.' }
        format.json { render :show, status: :created, location: @news_category }
      else
        format.html { render :new }
        format.json { render json: @news_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news_categories/1
  # PATCH/PUT /news_categories/1.json
  def update
    respond_to do |format|
      if @news_category.update(news_category_params)
        format.html { redirect_to @news_category, notice: 'News category was successfully updated.' }
        format.json { render :show, status: :ok, location: @news_category }
      else
        format.html { render :edit }
        format.json { render json: @news_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news_categories/1
  # DELETE /news_categories/1.json
  def destroy
    @news_category.destroy
    respond_to do |format|
      format.html { redirect_to news_categories_url, notice: 'News category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news_category
      @news_category = NewsCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_category_params
      params.require(:news_category).permit(:name)
    end
end

app/helpers/news_categories_helper.rb
module NewsCategoriesHelper
end

app/views/news_categories/_form.html.erb
<%= form_with(model: news_category, local: true) do |form| %>
  <% if news_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(news_category.errors.count, "error") %> prohibited this news_category from being saved:</h2>
      <ul>
        <% news_category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/news_categories/edit.html.erb
<h1>Editing News Category</h1>

<%= render 'form', news_category: @news_category %>

<%= link_to 'Show', @news_category %> |
<%= link_to 'Back', news_categories_path %>

app/views/news_categories/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Categories</h1>
<%= link_to '+ New', new_news_category_path, class: "controls-link block" %>
<br>
<br>
<br>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @news_categories.each do |news_category| %>
      <tr>
        <td><%= news_category.name %></td>
        <td><%= link_to 'Show', news_category %></td>
        <td><%= link_to 'Edit', edit_news_category_path(news_category) %></td>
        <td><%= link_to 'Destroy', news_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/news_categories/new.html.erb
<h1>New News Category</h1>

<%= render 'form', news_category: @news_category %>

<%= link_to 'Back', news_categories_path %>

app/views/news_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @news_category.name %>
</p>

<%= link_to 'Edit', edit_news_category_path(@news_category) %> |
<%= link_to 'Back', news_categories_path %>